# Copyright Contributors to the Open Cluster Management project
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-mce-config
data:
  LOG_LEVEL: info
  ansibleIntegration: disabled
  singleNodeOpenshift: disabled
  awsPrivateWizardStep: enabled
