
# Source: cluster-api-provider-aws/templates/rbac.authorization.k8s.io_v1_rolebinding_capa-leader-elect-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
  name: capa-leader-elect-rolebinding
  namespace: capa-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capa-leader-elect-role
subjects:
- kind: ServiceAccount
  name: capa-controller-manager
  namespace: capa-system
