# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

global:
  deployOnOCP: true
  imageOverrides: {}
  namespace: default
  pullSecret: null
  templateOverrides: {}
hubconfig:
  nodeSelector: null
  ocpVersion: 4.12.0
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
