global:
  imageOverrides:
    multicloud_manager: quay.io/test/test:test
  templateOverrides: {}
  pullSecret: ""
  namespace: default
  hubSize: Small
  deployOnOCP: ""
  servingCertCABundle: ""
hubconfig:
  nodeSelector: {}
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
  ocpVersion: "4.12.0"
org: open-cluster-management
