apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
  name: capi-selfsigned-issuer
  namespace: '{{ default "multicluster-engine" .Values.global.namespace }}'
spec:
  selfSigned: {}
