apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ .Values.org }}:{{ .Chart.Name }}:image-based-install-operator'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ .Values.org }}:{{ .Chart.Name }}:image-based-install-operator'
subjects:
- kind: ServiceAccount
  name: image-based-install-operator
  namespace: '{{ .Values.global.namespace }}'
