global:
  imageOverrides:
    multicloud_manager: quay.io/test/test:test
  pullSecret: ""
  namespace: default
hubconfig:
  nodeSelector: {}
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
