apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capoa-controlplane-cert
  namespace: '{{ .Values.global.namespace }}'
spec:
  commonName: capoa-controlplane-webhook-service.capoa-controlplane-system.svc
  dnsNames:
  - capoa-controlplane-webhook-service.capoa-controlplane-system.svc
  duration: 8760h
  issuerRef:
    kind: Issuer
    name: capoa-controlplane-selfsigned-issuer
  renewBefore: 360h
  secretName: capoa-controlplane-webhook-cert-secret
