apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capoa-controlplane-leader-election-rolebinding
  namespace: '{{ default "{{ .Values.global.namespace }}" .Values.global.namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capoa-controlplane-leader-election-role
subjects:
- kind: ServiceAccount
  name: capoa-controlplane-controller-manager
  namespace: '{{ default "{{ .Values.global.namespace }}" .Values.global.namespace }}'
