
# Copyright Contributors to the Open Cluster Management project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.org }}.cluster-lifecycle.cluster-image-set
subjects:
- kind: ServiceAccount
  name: cluster-image-set
  namespace: {{ .Values.global.namespace }}       ## CHANGE: ACM namespace
roleRef:
  kind: ClusterRole
  name: {{ .Values.org }}.cluster-lifecycle.cluster-image-set
  apiGroup: rbac.authorization.k8s.io
