apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: klusterletconfigs.config.open-cluster-management.io
spec:
  group: config.open-cluster-management.io
  names:
    kind: KlusterletConfig
    listKind: KlusterletConfigList
    plural: klusterletconfigs
    singular: klusterletconfig
  preserveUnknownFields: false
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KlusterletConfig contains the configuration of a klusterlet including
          the upgrade strategy, config overrides, proxy configurations etc.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of KlusterletConfig
            properties:
              appliedManifestWorkEvictionGracePeriod:
                description: AppliedManifestWorkEvictionGracePeriod is the eviction
                  grace period the work agent will wait before evicting the AppliedManifestWorks,
                  whose corresponding ManifestWorks are missing on the hub cluster,
                  from the managed cluster. If not present, the default value of the
                  work agent will be used. If its value is set to "INFINITE", it means
                  the AppliedManifestWorks will never been evicted from the managed
                  cluster.
                pattern: ^([0-9]+(s|m|h))+$|^INFINITE$
                type: string
              hubKubeAPIServerCABundle:
                description: 'HubKubeAPIServerCABundle is the CA bundle to verify
                  the server certificate of the hub kube API against. If not present,
                  CA bundle will be determined with the logic below: 1). Use the certificate
                  of the named certificate configured in APIServer/cluster if FQDN
                  matches; 2). Otherwise use the CA certificates from kube-root-ca.crt
                  ConfigMap in the cluster namespace;'
                format: byte
                type: string
              hubKubeAPIServerProxyConfig:
                description: HubKubeAPIServerProxyConfig holds proxy settings for
                  connections between klusterlet/add-on agents on the managed cluster
                  and the kube-apiserver on the hub cluster. Empty means no proxy
                  settings is available.
                properties:
                  caBundle:
                    description: CABundle is a CA certificate bundle to verify the
                      proxy server. It will be ignored if only HTTPProxy is set; And
                      it is required when HTTPSProxy is set and self signed CA certificate
                      is used by the proxy server.
                    format: byte
                    type: string
                  httpProxy:
                    description: HTTPProxy is the URL of the proxy for HTTP requests
                    type: string
                  httpsProxy:
                    description: HTTPSProxy is the URL of the proxy for HTTPS requests
                      HTTPSProxy will be chosen if both HTTPProxy and HTTPSProxy are
                      set.
                    type: string
                type: object
              hubKubeAPIServerURL:
                description: HubKubeAPIServerURL is the URL of the hub Kube API server.
                  If not present, the .status.apiServerURL of Infrastructure/cluster
                  will be used as the default value. e.g. `oc get infrastructure cluster
                  -o jsonpath='{.status.apiServerURL}'`
                type: string
              nodePlacement:
                description: NodePlacement enables explicit control over the scheduling
                  of the agent components. If the placement is nil, the placement
                  is not specified, it will be omitted. If the placement is an empty
                  object, the placement will match all nodes and tolerate nothing.
                properties:
                  nodeSelector:
                    additionalProperties:
                      type: string
                    description: NodeSelector defines which Nodes the Pods are scheduled
                      on. The default is an empty list.
                    type: object
                  tolerations:
                    description: Tolerations is attached by pods to tolerate any taint
                      that matches the triple <key,value,effect> using the matching
                      operator <operator>. The default is an empty list.
                    items:
                      description: The pod this Toleration is attached to tolerates
                        any taint that matches the triple <key,value,effect> using
                        the matching operator <operator>.
                      properties:
                        effect:
                          description: Effect indicates the taint effect to match.
                            Empty means match all taint effects. When specified, allowed
                            values are NoSchedule, PreferNoSchedule and NoExecute.
                          type: string
                        key:
                          description: Key is the taint key that the toleration applies
                            to. Empty means match all taint keys. If the key is empty,
                            operator must be Exists; this combination means to match
                            all values and all keys.
                          type: string
                        operator:
                          description: Operator represents a key's relationship to
                            the value. Valid operators are Exists and Equal. Defaults
                            to Equal. Exists is equivalent to wildcard for value,
                            so that a pod can tolerate all taints of a particular
                            category.
                          type: string
                        tolerationSeconds:
                          description: TolerationSeconds represents the period of
                            time the toleration (which must be of effect NoExecute,
                            otherwise this field is ignored) tolerates the taint.
                            By default, it is not set, which means tolerate the taint
                            forever (do not evict). Zero and negative values will
                            be treated as 0 (evict immediately) by the system.
                          format: int64
                          type: integer
                        value:
                          description: Value is the taint value the toleration matches
                            to. If the operator is Exists, the value should be empty,
                            otherwise just a regular string.
                          type: string
                      type: object
                    type: array
                type: object
              pullSecret:
                description: PullSecret is the name of image pull secret.
                properties:
                  apiVersion:
                    description: API version of the referent.
                    type: string
                  fieldPath:
                    description: 'If referring to a piece of an object instead of
                      an entire object, this string should contain a valid JSON/Go
                      field access statement, such as desiredState.manifest.containers[2].
                      For example, if the object reference is to a container within
                      a pod, this would take on a value like: "spec.containers{name}"
                      (where "name" refers to the name of the container that triggered
                      the event) or if no container name is specified "spec.containers[2]"
                      (container with index 2 in this pod). This syntax is chosen
                      only to have some well-defined way of referencing a part of
                      an object. TODO: this design is not final and this field is
                      subject to change in the future.'
                    type: string
                  kind:
                    description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                    type: string
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                    type: string
                  namespace:
                    description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                    type: string
                  resourceVersion:
                    description: 'Specific resourceVersion to which this reference
                      is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                    type: string
                  uid:
                    description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                    type: string
                type: object
              registries:
                description: Registries includes the mirror and source registries.
                  The source registry will be replaced by the Mirror.
                items:
                  properties:
                    mirror:
                      description: Mirror is the mirrored registry of the Source.
                        Will be ignored if Mirror is empty.
                      type: string
                    source:
                      description: Source is the source registry. All image registries
                        will be replaced by Mirror if Source is empty.
                      type: string
                  required:
                  - mirror
                  type: object
                type: array
            type: object
          status:
            description: Status defines the observed state of KlusterletConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
