# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Service
metadata:
  name: ocm-proxyserver
  labels:
    control-plane: ocm-proxyserver
    ocm-antiaffinity-selector: ocm-proxyserver
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ocm-proxyserver
spec:
  ports:
    - port: 443
      targetPort: 6443
      name: secure
      protocol: TCP
  selector:
    control-plane: ocm-proxyserver