apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capoa-controlplane-cert
  namespace: '{{ default "capoa-controlplane-system" .Values.global.namespace }}'
spec:
  commonName: capoa-controlplane-webhook-service.{{ default "capoa-controlplane-system" .Values.global.namespace }}.svc
  dnsNames:
  - capoa-controlplane-webhook-service.{{ default "capoa-controlplane-system" .Values.global.namespace }}.svc
  duration: 8760h
  issuerRef:
    kind: Issuer
    name: capoa-controlplane-selfsigned-issuer
  renewBefore: 360h
  secretName: capoa-controlplane-webhook-cert-secret
