global:
  deployOnOCP: true
  imageOverrides:
    assisted_image_service: ''
    assisted_installer: ''
    assisted_installer_agent: ''
    assisted_installer_controller: ''
    assisted_service_8: ''
    assisted_service_9: ''
    postgresql_12: ''
  namespace: default
  pullSecret: null
  templateOverrides: {}
hubconfig:
  nodeSelector: null
  ocpVersion: 4.12.0
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
