# Copyright Contributors to the Open Cluster Management project
apiVersion: v1
appVersion: "2.0.0"
description: Helm chart for MultiCluster Engine Console
name: console-mce
version: 2.0.0
category: "Development"
kubeVersion: ">=1.10.0-0"
keywords:
  - ui
