apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: mce-capm3-leader-election-rolebinding
  namespace: '{{ default "capm3-system" .Values.global.namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mce-capm3-leader-election-role
subjects:
- kind: ServiceAccount
  name: mce-capm3-manager
  namespace: '{{ default "capm3-system" .Values.global.namespace }}'
