apiVersion: v1
data:
  CAPM3_FAST_TRACK: ${CAPM3_FAST_TRACK:='false'}
kind: ConfigMap
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: capm3-capm3fasttrack-configmap
  namespace: '{{ default "{{ .Values.global.namespace }}" .Values.global.namespace }}'
