apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-metal3
  name: mce-capm3-serving-cert
  namespace: '{{ default "multicluster-engine" .Values.global.namespace }}'
spec:
  commonName: mce-capm3-webhook-service.{{ default "multicluster-engine" .Values.global.namespace }}.svc
  dnsNames:
  - mce-capm3-webhook-service.{{ default "multicluster-engine" .Values.global.namespace }}.svc
  - mce-capm3-webhook-service.{{ default "multicluster-engine" .Values.global.namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: mce-capm3-selfsigned-issuer
  secretName: mce-capm3-webhook-service-cert
