global:
  deployOnOCP: true
  hubSize: Small
  imageOverrides:
    openshift_hive: ''
  namespace: default
  pullSecret: null
  templateOverrides: {}
hubconfig:
  nodeSelector: null
  ocpVersion: 4.12.0
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
