apiVersion: v2
appVersion: 2.7.0
description: This operator discovers OpenShift Conatiner Platform clusters which are
  not yet under management by Open Cluster Management.
name: capi-core-operator
type: application
version: 2.7.0
