global:
  pullPolicy: Always
  namespace: default
  pullSecret: null
  imageOverrides:
    cluster_proxy_addon: ""
    cluster_proxy: ""
  templateOverrides: {}
hubconfig:
  nodeSelector: null
  replicaCount: 1
  proxyConfigs: {}
  tolerations: []
  ocpVersion: "4.12.0"
org: open-cluster-management

