apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: azureserviceoperator-serving-cert
  namespace: '{{ .Values.global.namespace }}'
spec:
  dnsNames:
  - azureserviceoperator-webhook-service.{{ .Values.global.namespace }}.svc
  - azureserviceoperator-webhook-service.{{ .Values.global.namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: azureserviceoperator-selfsigned-issuer
  secretName: webhook-server-cert
  subject:
    organizations:
    - azure
