apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
    service.beta.openshift.io/serving-cert-secret-name: webhook-server-cert
  labels:
    app.kubernetes.io/name: azure-service-operator
    app.kubernetes.io/version: v2.13.0-hcpclusters.1
  name: azureserviceoperator-webhook-service
  namespace: '{{ default "capz-system" .Values.global.namespace }}'
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: controller-manager
