apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
  name: capz-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azurecluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.azurecluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azureclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azureclustertemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.azureclustertemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azureclustertemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.azuremachine.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.azuremachinetemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachinetemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremanagedcontrolplane
  failurePolicy: Fail
  name: default.azuremanagedcontrolplanes.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremanagedcontrolplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremanagedcontrolplanetemplate
  failurePolicy: Fail
  name: default.azuremanagedcontrolplanetemplates.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremanagedcontrolplanetemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremanagedmachinepool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.azuremanagedmachinepools.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremanagedmachinepools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremanagedmachinepooltemplate
  failurePolicy: Fail
  name: default.azuremanagedmachinepooltemplates.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremanagedmachinepooltemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta2
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta2-aromachinepool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.aromachinepools.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - aromachinepools
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta2
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-controlplane-cluster-x-k8s-io-v1beta2-arocontrolplane
  failurePolicy: Fail
  name: default.arocontrolplanes.controlplane.cluster.x-k8s.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - arocontrolplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: capz-webhook-service
      namespace: '{{ default "capz-system" .Values.global.namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-azuremachinepool
  failurePolicy: Fail
  name: default.azuremachinepool.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - azuremachinepools
  sideEffects: None
