
# Source: cluster-api-provider-azure/templates/v1_namespace_capz-system.yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
    pod-security.kubernetes.io/enforce: privileged
  name: capz-system
