apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: azure-service-operator
    app.kubernetes.io/version: v2.13.0-hcpclusters.1
    control-plane: azureserviceoperator-controller-manager
  name: azureserviceoperator-controller-manager-metrics-service
  namespace: '{{ .Values.global.namespace }}'
spec:
  ports:
  - name: metrics
    port: 8443
  selector:
    control-plane: azureserviceoperator-controller-manager
