apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
  name: capz-serving-cert
  namespace: '{{ .Values.global.namespace }}'
spec:
  dnsNames:
  - capz-webhook-service.{{ .Values.global.namespace }}.svc
  - capz-webhook-service.{{ .Values.global.namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capz-selfsigned-issuer
  secretName: capz-webhook-service-cert
