# This is a basic workflow to help you get started with Actions

name: Regenerate Operator Bundles

# Controls when the action will run. 
on:
  # Runs every six hours
  schedule:
    - cron: "0 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # If one jobs fail, we still want the other jobs to run.
      matrix:
        python-version: [3.9]
        branch: ['main', 'backplane-2.5', 'backplane-2.6', 'backplane-2.7', 'backplane-2.8', 'backplane-2.9', 'backplane-2.10']
        include:
          - branch: backplane-2.5
            go-version: "1.20"
          - branch: backplane-2.6
            go-version: "1.21"
          - branch: backplane-2.7
            go-version: "1.24"
          - branch: backplane-2.8
            go-version: "1.24"
          - branch: backplane-2.9
            go-version: "1.24"
          - branch: backplane-2.10
            go-version: "1.24"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BACKPLANE_TOKEN }}
          ref: ${{ matrix.branch }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }} # Specify the Go version from the matrix

      # TODO: Re-enable linting bundle after squads address CSV issues.
      # Runs a set of commands using the runners shell
      # - name: Lint Operator Bundles
      #   id: lint_bundle
      #   run: |
      #     make lint-operator-bundles
      #     exit_code=$?
      #     if [ $exit_code -ne 0 ]; then
      #       echo "Lint Operator Bundles step failed with exit code $exit_code"
      #       exit $exit_code
      #     fi

      # Runs a set of commands using the runners shell
      - name: Regenerate Operator Charts From Bundles
        id: generate_charts_from_bundles
        run: |
          make regenerate-charts-from-bundles
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Regenerate Operator Charts From Bundles step failed with exit code $exit_code"
            exit $exit_code
          fi

      - name: Generate code
        run: |
          echo "Running go generate..."
          go generate
  
      - name: Generate Manifests
        run: |
          echo "Generating manifests..."
          make manifests

      - name: Send Slack Message on Failure
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          SLACK_MESSAGE=":exclamation: *GitHub Actions Job Failed* :exclamation:\n\n"
          SLACK_MESSAGE+="Job Name: $GITHUB_WORKFLOW/$GITHUB_JOB\n"
          SLACK_MESSAGE+="Job URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\n"
          SLACK_MESSAGE+="Error Details: Your job failed. Please check the job logs for more information."

          curl -X POST -H "Content-type: application/json" --data "{
            \"text\": \"$SLACK_MESSAGE\"
          }" $SLACK_WEBHOOK_URL
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          signoff: true
          branch: "regenerate-operator-bundles-${{ matrix.branch }}"
          delete-branch: true
          title: "Operator Bundle Update [${{ matrix.branch }}]"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          labels: |
            do-not-merge/hold
            ok-to-test
          reviewers: cameronmwall,dislbenn,ngraham20
