apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  creationTimestamp: null
  name: mce-capi-webhook-config-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  - v1alpha1
  clientConfig:
    service:
      name: mce-capi-webhook-config-service
      namespace: '{{ default "capi-system" .Values.global.namespace }}'
      path: /mutate
      port: 9443
  failurePolicy: Fail
  name: mce-capi-webhook-config.x-k8s.io
  rules:
  - apiGroups:
    - cluster.x-k8s.io
    - ipam.cluster.x-k8s.io
    - runtime.cluster.x-k8s.io
    - addons.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
    scope: Namespaced
  sideEffects: None
