global:
  imageOverrides:
    openshift_hive: ''
  pullPolicy: Always
  pullSecret: null
hubconfig:
  nodeSelector: null
  proxyConfigs: {}
  replicaCount: 1
  tolerations: []
org: open-cluster-management
